# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

steps:

#- bash: "sudo apt-get install -y ffmpeg xvfb freeglut3-dev python-opengl --fix-missing"
#  displayName: 'Install ffmpeg, freeglut3-dev, and xvfb'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'

#- script: sh ./build/azure_pipeline_helper.sh
#  displayName: 'Complex Installs'

- script: |
#    pip install Bottleneck
#    pip install moviepy
    python setup.py install
    pip install pytest
    pip install pytest-cov
  displayName: 'Install Python Packages'

- script: |
    xvfb-run -s "-screen 0 1400x900x24" pytest tests --doctest-modules --junitxml=junit/test-results.xml --cov=./ --cov-report=xml --cov-report=html
  displayName: 'Test with pytest'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: '**/test-*.xml'
    testRunTitle: 'Publish test results for Python $(python.version)'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'