# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:

- bash: "sudo apt-get install -y ffmpeg xvfb freeglut3-dev python-opengl"
  displayName: 'Install ffmpeg, freeglut3-dev, and xvfb'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'

- script: pip install Bottleneck pytest pytest-xdist
  displayName: 'Install sensitive packages'

- script: sh ./build/azure_pipeline_helper.sh
  displayName: 'Complex Installs'

- script: python setup.py install
  displayName: 'Run a multi-line script'

- script: xvfb-run -s "-screen 0 1400x900x24" pytest -n 8 fast_rl/tests
  displayName: 'Test with pytest'
