# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'

- script: pip install Bottleneck pytest pytest-xdist
  displayName: 'Install sensitive packages'

- script: python setup.py install
  displayName: 'Run a multi-line script'

- script: pytest -n 8 fast_rl/tests
  displayName: 'Test with pytest'
